savekerala/mainapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name="mainapp"

urlpatterns = [
    path('home/', views.home,name="home"),
    path('helplinenumbers/', views.helplinenumbers,name="helplinenumbers"),
    path('disastercamps/', views.disastercamps,name="disastercamps"),
    path('floodmaps/', views.floodmaps,name="floodmaps"),
]

savekerala/savekerala/urls.py
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'),name='mainapp'),
]

savekerala/mainapp/models.py
from django.db import models
from django import forms

class helplinenumber(models.Model):
	name=models.CharField(max_length=255,blank=True)
	phonenumber=models.BigIntegerField(blank=True)
	def __str__(self):
		return self.name
class news(models.Model):
	desc=models.CharField(max_length=25500,blank=True)
	photo=models.FileField(blank=True)
	def __str__(self):
		return self.desc

savekerala/mainapp/forms.py
from .models import *

class helplinenumberForm(forms.ModelForm):
	class Meta:
		model=helplinenumber
		fields=('name','phonenumber')

class newsForm(forms.ModelForm):
	class Meta:
		model=news
		fields=('desc','photo')

savekerala/mainapp/views.py
import time
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse

from django.views import View

from .forms import *
from .models import *

def home(request):
	data={}
	all_news=news.objects.all()
	data['all_news']=all_news
	if request.method == 'POST':
		form=newsForm(request.POST,request.FILES)
		print(request.FILES)
		if form.is_valid():
			form.save()
			return redirect('/home')
		else:
			return redirect('/helplinenumbers')
	else:
		form=newsForm()
		data['form']=form
		return render(request,'mainapp/index.html',data)

def helplinenumbers(request):
	data={}
	all_helplinenumber=helplinenumber.objects.all()
	data['all_helplinenumber']=all_helplinenumber
	if request.method == 'POST':
		form = helplinenumberForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/helplinenumbers')
		else:
			return redirect('/home')
	else:
		form=helplinenumberForm()
		data['form']=form
		return render(request,'mainapp/no.html',data)

def disastercamps(request):
	data={}
	return render(request,'mainapp/disaster.html',data)

def floodmaps(request):
	data={}
	return render(request,'mainapp/floodmaps.html',data)

savekerala/mainapp/templates/mainapp/base.html
{% load staticfiles %}
<html>
<head>
	<title> DO FOR KERALA:authenticate news </title>
	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<script type="text/javascript" src="{% static 'jav.js' %}"></script>
</head>
<body class="bod">

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>                        
				</button>
				<a class="navbar-brand logofont" href="{% url 'mainapp:home' %}">AUTHENTICATE DISASTER NEWS</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="homefont {% block helplinenumbers %}{% endblock %}" ><a href="{% url 'mainapp:helplinenumbers' %}">HELPLINE NUMBERS</a></li>
					<li class="homefont {% block disastercamps %}{% endblock %}" ><a href="{% url 'mainapp:disastercamps' %}">RELIEF CAMPS</a></li>
					<li class="homefont {% block floodmaps %}{% endblock %}"><a href="{% url 'mainapp:floodmaps' %}">FLOOD MAPS</a></li>
					<li><a href="#">FOOD COLLECTION POINTS</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
					<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
				</ul>
			</div>
		</div>
	</nav>
	<div class="container">
		<div >
		<h1 class="d" style="display: inline;">DO</h1>
		<h1 class="topic">FOR KERALA.</h1>
		</div>
		<hr>
	</div>	
	<div class="container">
		{% block body %}
		{% endblock %}
	</div>

	{% block javascript %}
	{% endblock %}
</body>
</html>

savekerala/mainapp/templates/mainapp/disaster.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block disastercamps %}active{% endblock %}
{% block body %}
	<h2 class="cl" style="font-style: italic;">UPLOAD RELIEF CAMP ADDRESS HERE </h1>
	<br>
	<label class="cl">ADDRESS:
	</label>
	<br>
	<textarea row="50" cols="45"></textarea>
	<button style="color: black;">Add</button>
	<br>
	<br>
	<p style="font-size: 200%; " class="cl">UPLOADED ADDRESS:</p>
{% endblock %}

savekerala/mainapp/templates/mainapp/floodmaps.html
{% extends 'mainapp/base.html' %}
{% block floodmaps %}active{% endblock %}
{% block body %}
{% endblock %}

savekerala/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block home %}active{%  endblock %}
{% block body %}
	<!-- <div >
		<h1 class="d" style="display: inline;">DO</h1>
		<h1 class="topic">FOR KERALA.</h1>
		
	</div> -->
	<!-- <hr> -->
	<p class="cl" style="font-size: 150%;font-style: italic;">
		This site aims at filtering the fake news from the real ones.Kerala
		is facing a crisis and we need the help of all the people in kerala to help 
		this site with data.
	</p>
	<p class="cl" style="font-size: 150%;font-style: italic;">
		anyone can upload relavent news,warnings,helplines numbers,relief camp addressess here or even attach social meadia spread news.Users can then upvote or downvote on them and use the ratings to authenticate the news. 

		
	</p>
	<br>
	<br>
	<div class="h">
		<h2 class="cl">UPLOAD NEWS HERE</h1>
	</div>

	<div class="h">
		<label for="user" class="cl">Type news here:</label> 
		<br>
		<textarea row="50" cols="45"></textarea>
		<br>
		<br>
		<br>
		<label for="doc" class="cl"> Upload supporting documents/images </label>
		<input type="file" name="docs" id="doc" accept="image/*" style="color: white;">
		<br>
		<button>upload</button>
	</div>
	<br>
	<!-- <form action="{% url 'mainapp:home' %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit" style="color: black;" />
	</form> -->
	<p style="font-size: 200%;" class="cl">
	CURRENTLY UPLOADED NEWS :
	</p>
{% endblock %}

savekerala/mainapp/templates/mainapp/no.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block helplinenumbers %}active{%  endblock %}
{% block body  %}
	<h2 class="cl" style="font-style: italic;">UPLOAD HELPLINE NUMBERS HERE </h1>
	<br>
	<br>
<!-- 	<p class="cl" style="font-size: 150%;font-style: italic;">Upload helpline numbers here</p>
 -->	<form action="{% url 'mainapp:helplinenumbers' %}" method="post" class="cl">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit" style="color: black;" />
	</form>
	<br>
	<br>
	
	<p style="font-size: 200%;" class="cl">UPLOADED NUMBERS:</p>
	<table border="1" bordercolor="WHITE" class="helplinenumberstable" >
		<tr class="cl">
			<th>NAME</th>
			<th>NUMBER</th>
		</tr>
		{% for i in all_helplinenumber %}
			<tr class="cl">
				<td>{{ i.name }}</td>
				<td>{{ i.phonenumber }}</td>
			</tr>
		{% endfor %}
	</table>
{% endblock %}